name: train-my-model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --no-cache-dir "poetry==1.1.4"
          poetry config virtualenvs.create false
          poetry install --no-dev --no-interaction --no-ansi

          # Build and publish image with API REST
